---
apiVersion: v1
kind: Namespace
metadata:
  name: invoices
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: "invoices-web"
  name: "invoices-web"
  namespace: invoices
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: "invoices-web"
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: "invoices-web"
      namespace: invoices
      annotations:
        linkerd.io/inject: disabled
    spec:
      nodeSelector:
        doks.digitalocean.com/node-pool: notessimo-web
      imagePullSecrets:
        - name: github-registry
      containers:
        - image: ghcr.io/starburst997/invoices-web:latest
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 80
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
            initialDelaySeconds: 60
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 80
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
            initialDelaySeconds: 30
          name: "invoices-web"
          ports:
            - containerPort: 80
              protocol: TCP
          resources:
            requests:
              cpu: 1m
              memory: 32Mi
              ephemeral-storage: 256Mi
            limits:
              cpu: 150m
              memory: 256Mi
              ephemeral-storage: 512Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: "invoices-web"
  name: "invoices-web"
  namespace: invoices
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: "invoices-web"
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: invoices
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/limit-rpm: "1000"
    nginx.ingress.kubernetes.io/limit-whitelist: "10.0.0.0/8"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-ciphers: "HIGH:!aNULL:!MD5"
  name: invoices-web
spec:
  tls:
    - hosts:
        - invoices.boiv.in
      secretName: invoices-web-tls
  rules:
    - host: invoices.boiv.in
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: invoices-web
                port:
                  number: 80
